# Generated by Django 5.2.3 on 2025-07-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MonthlyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(5, 'Май'), (6, 'Юни'), (7, 'Юли'), (8, 'Август'), (9, 'Септември')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_prices', to='listings.listing')),
            ],
            options={
                'unique_together': {('listing', 'month')},
            },
        ),
    ]
