# Generated by Django 5.2.3 on 2025-07-27 11:31

import django.core.validators
import listings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='Описанието трябва да е по-дълго.')]),
        ),
        migrations.AlterField(
            model_name='camping',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message='Заглавието трябва да е по-дълго.')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='listing_images/', validators=[listings.validators.ListingImageFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='Описанието трябва да е по-дълго.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_nights',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mini_description',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Подзаглавието трябва да е поне 3 символа.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(10, message='Цената е прекалено ниска.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Мястото трябва да има поне една стая.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_meters',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Заглавието трябва да е поне 3 символа.')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='Улица 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Veliko Tarnovo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(10, message='Цената е прекалено ниска.')]),
        ),
    ]
