# Generated by Django 5.2.3 on 2025-08-02 13:56

import cloudinary.models
import listings.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_camping_description_alter_camping_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[listings.validators.ListingImageFileSizeValidator(5)], verbose_name='image'),
        ),
    ]
