# Generated by Django 5.2.3 on 2025-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_blogpostblock_image_alter_blogpostblock_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='nai-dobrata-novina', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
