# Generated by Django 5.2.3 on 2025-07-27 10:35

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='Георги', max_length=30, validators=[accounts.validators.name_validator_only_letters, django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='Георгиев', max_length=30, validators=[accounts.validators.name_validator_only_letters, django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[accounts.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0897453678', max_length=15, validators=[django.core.validators.MinLengthValidator(9)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[accounts.validators.ProfilePictureFileSizeValidator(3)]),
        ),
    ]
