# Generated by Django 5.2.3 on 2025-07-27 11:31

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_email_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.name_validator_only_letters, django.core.validators.MinLengthValidator(3, message='Името трябва да е поне 3 символа.')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.name_validator_only_letters, django.core.validators.MinLengthValidator(3, message='Името трябва да е поне 3 символа.')]),
        ),
    ]
